node {
   def commit_id
   stage('Preparation') {
      steps{
        checkout scm
        sh "git rev-parse --short HEAD > .git/commit-id"                        
        commit_id = readFile('.git/commit-id').trim()
      }
   }

   stage('Installation & Test') {
      steps{
        sh '''
        npm install --only=dev'
        npm test
        '''
      }
   }

    stage('Build & Push image') {
      steps{
        withDockerRegistry([ credentialsId: "dockerhub", url: "" ]) {
        sh '''
        docker build -t cbalcazarp/repo-devops-challenge:${commit_id} .
        docker push cbalcazarp/repo-devops-challenge:${commit_id}
        '''
        }
      }
    }

}