node {
  def commit_id
  stage('Preparation') {
    checkout scm
    sh "git rev-parse --short HEAD > .git/commit-id"                        
    commit_id = readFile('.git/commit-id').trim()
  }
  stage('Installation & Test') {
    sh 'npm install --only=dev'
    sh 'npm test'
  }
  stage('Build & Push image') {
    withDockerRegistry([ credentialsId: "dockerhub", url: "" ]) {
      sh "docker build -t cbalcazarp/repo-devops-challenge:${commit_id} ."
      sh "docker push cbalcazarp/repo-devops-challenge:${commit_id}"
    }
    echo "${commit_id}"
  }
  stage('Deploy to Server vmalpha') {
    sh "ssh -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa_alpha jenkins@3.208.20.126"
    sh "docker run -d --user root -p 8080:8080 cbalcazarp/repo-devops-challenge:${commit_id}"
    
  }
}