node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
  
       sh 'npm install --only=dev'
       sh 'npm test'
    
   }
    stage('Push image') {
            withDockerRegistry([ credentialsId: "dockerhub", url: "" ]) {
            sh "docker build -t cbalcazarp/repo-devops-challenge:latest ."
            sh "docker push cbalcazarp/repo-devops-challenge:latest"
            }
    }

}